#  +----------------------------------------------------------+
#  |                    AzisabaReport plugin                  |
#  |                                                          |
#  | GitHub : https://github.com/AzisabaNetwork/AzisabaReport |
#  +----------------------------------------------------------+

ReportURL:
ReportBugURL:

ReportMention:
ReportBugMention:

ReportCT:
